export enum processTypes {
    CHANGE_STEP = "CHANGE_STEP",
    SET_INTERVAL_ID = "SET_INTERVAL_ID",
  }

export enum stepTypes {
    PRISTINE = "PRISTINE",
    TAKING_PHOTO = "TAKING_PHOTO",
    PROCESSING_PHOTO = "PROCESSING_PHOTO",
    PHOTO_REJECTED = "PHOTO_REJECTED",
    PHOTO_ACCEPTED = "PHOTO_ACCEPTED"
}
