export enum verificationTypes {
    FETCH_VERIFICATION_REQUEST = "FETCH_VERIFICATION_REQUEST",
    FETCH_VERIFICATION_SUCCESS = "FETCH_VERIFICATION_SUCCESS",
    FETCH_VERIFICATION_FAILURE = "FETCH_VERIFICATION_FAILURE",
    SAVE_APPROVED_PHOTO = "SAVE_APPROVED_PHOTO",
  }
